version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: sneakers
      POSTGRES_USER: sneakers
      POSTGRES_PASSWORD: sneakers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
